### ISSUE TITLE
"Assertion Error" on "Component Evaluation" step when running .avi's 

### ISSUE THREAD

**Issue by jtalley24** [flatironinstitute/CaImAn#322]
- Windows 10, Python 3, Jupyter Notebook

- When I run certain .avi's (generally longer ones, though not sure that is my issue), I receive the error below in an infinite loop in Git Bash until I shut the program down.  No error message appears in Jupyter, but it never completes the Component Evaluation step of the pipeline.

- AssertionError
Process SpawnPoolWorker-6823:
Traceback (most recent call last):
  File "C:\Users\FuccilloLab\Anaconda3\envs\caiman\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\FuccilloLab\Anaconda3\envs\caiman\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\FuccilloLab\Anaconda3\envs\caiman\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Users\FuccilloLab\Anaconda3\envs\caiman\lib\multiprocessing\queues.py", line 335, in get
    res = self._reader.recv_bytes()
  File "C:\Users\FuccilloLab\Anaconda3\envs\caiman\lib\multiprocessing\connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "C:\Users\FuccilloLab\Anaconda3\envs\caiman\lib\multiprocessing\connection.py", line 318, in _recv_bytes
    return self._get_more_data(ov, maxsize)
  File "C:\Users\FuccilloLab\Anaconda3\envs\caiman\lib\multiprocessing\connection.py", line 337, in _get_more_data
    assert left > 0
AssertionError
Process SpawnPoolWorker-6826:
Traceback (most recent call last):
  File "C:\Users\FuccilloLab\Anaconda3\envs\caiman\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\FuccilloLab\Anaconda3\envs\caiman\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\FuccilloLab\Anaconda3\envs\caiman\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Users\FuccilloLab\Anaconda3\envs\caiman\lib\multiprocessing\queues.py", line 335, in get
    res = self._reader.recv_bytes()
  File "C:\Users\FuccilloLab\Anaconda3\envs\caiman\lib\multiprocessing\connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "C:\Users\FuccilloLab\Anaconda3\envs\caiman\lib\multiprocessing\connection.py", line 318, in _recv_bytes
    return self._get_more_data(ov, maxsize)
  File "C:\Users\FuccilloLab\Anaconda3\envs\caiman\lib\multiprocessing\connection.py", line 337, in _get_more_data
    assert left > 0

Any help as to why this error is occurring is greatly appreciated.  It only occurs on some videos, but all of my videos have the same FOV.

**Comment by agiovann** [comment]
Hello @jtalley24 , try two possible solutions:
set dview = None
or set parallelization  backend to ipyparallel instead of local

Let me know if any of this works

**Comment by jtalley24** [comment]
Thank you for the quick response!  Setting dview = none solved my issue.

However, the pipeline still takes ~20 minutes on a 480x752 video of ~30 seconds.  I read in this paper "Efficient and accurate extraction of in vivo calcium signals from microendoscopic video data" (https://elifesciences.org/articles/28728) that the MATLAB implementation has three different modes, including a "patch-mode" and "multi-batch mode" for faster processing.  Do the same modes exist for the Python implementation, and how may I use them if so?  I am running on a 6-core standalone PC.

**Comment by agiovann** [comment]
@jtalley24  Does it work with backend ipyparallel?

**Comment by jtalley24** [comment]
Yes, it also works with backend ipyparallel in addition to dview = none, but at a similar speed.  Would it be different or worthwhile to try it with dview=dview and backend ipyparallel?

**Comment by agiovann** [comment]
@jtalley24 if you used demo_pipeline_cnmfE.py then it is in patches (if you do not set dview=None at the same time!, meaning dview=dview), you can select how many processes you want to use and you can get better performance at the expenses of more memory. Have you set the environment variable set to 

export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1

**Comment by jtalley24** [comment]
I don't believe I have set the environment variables, how do I do this on windows 10 / Jupyter?  In the meantime I will try with dview = dview and backend ipyparallel

**Comment by jtalley24** [comment]
Update:  Does not work with backend ipyparallel AND dview = dview.  Only appears to run fully when dview = None in the "Component Evaluation" step.

when dview = dview and parallelization backend is ipyparallel, I receive a message:
"**** Unrecognized syntax in ipcluster output, waiting for server to stop anyways ****"
and a "Timeout" error.

**Comment by jtalley24** [comment]
Not sure why this was closed.  Both above questions / issues remain.

**Comment by epnev** [comment]
@jtalley24 The environment variables can be set in your terminal/command prompt once you activate your environment and before you launch your python editor/notebook. For example:
```
activate CaImAn
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
jupyter notebook
```

**Comment by pgunn** [comment]
@epnev I think the user is on Windows.

@jtalley24 To set those env vars, you should be able to do

set MKL_NUM_THREADS=1
set OPENBLAS_NUM_THREADS=1
and then launch jupyter

See if that helps; one other thing you might try is increase your swap size (which on Windows limits the size of possible memmap operations as a side effect).

**Comment by epnev** [comment]
@jtalley24 Let us know if your issue persists. Otherwise, we'll close it.

**Comment by jtalley24** [comment]
Even after setting the environment variables, it still does not work with backend 'ipyparallel' and dview = dview.  It works fine with backend 'local' and dview = none, but just as slow as initially.  About ~20-25 min for a 40 second, 480x752 video on a 6 core standalone pc.

**Comment by epnev** [comment]
How about ` backend='local'` and `dview=dview`? If `n_processes > 1`, you use patches and your memory can handle it, it should be faster (if it goes through).

FYI, If you set `dview=None`then no parallel processing is being used and the `backend` variable is irrelevant.

**Comment by jtalley24** [comment]
backend = 'local' and 'dview = dview' yields the Assertion Error I opened this issue with.  It only goes through when I change it to 'dview = None' in the "Component Evaluation" section (but don't need to do so anywhere else it seems).

**Comment by pgunn** [comment]
Which branch are you on? Master or dev? Also, if you can try to find the smallest file you have that reliably creates problems, I can see if I can reproduce it locally.

**Comment by jtalley24** [comment]
Sorry @pgunn did not see your response last week.  I believe I am on master... how do I tell which branch?

Returning to this issue because I believe parallel processing is in fact necessary given my machine's specs.  Tried running 10 videos through for concatenated analysis which caused my CPU to crash this morning on the Motion Correction step, so parallel processing with the GPU seems necessary.  

here's a ~30 second .avi that has been yielding the above issues when I try to use parallel processing: https://drive.google.com/file/d/1C0GclQE53Z_f6kILiJGz6owLIe-Q7AYy/view

Let me know if that works or if there is an easier way to send you the test file.

**Comment by pgunn** [comment]
If you do a `git branch` in your sourcetree it should tell you.

**Comment by jtalley24** [comment]
So any suggestions on how to get parallel processing working?  I also have `n_processes = 24` , would change that parameter affect anything in this case?  Still cannot run with `backend = 'ipyparallel'` or `dview = dview` (explained more in detail above)...

**Comment by epnev** [comment]
@jtalley24 I'm actually not sure that you have tried running with `dview=dview` and `backend='local'` *after* setting the environment variables as described above. If you have, then be patient and we might look into this at some point.

**Comment by jtalley24** [comment]
after setting the environment environment variables and `dview=dview` and `backend=local`, I receive a new error, still on the component evaluation step:

`---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
<ipython-input-15-d0ab9641663e> in <module>()
      8                             Y, cnm.A, cnm.C, cnm.b, cnm.f, cnm.YrA, frate,
      9                             decay_time, gSig, dims, dview=dview,
---> 10                             min_SNR=min_SNR, r_values_min=r_values_min, use_cnn=False)
     11 
     12 print(' ***** ')

~\Anaconda3\envs\caiman\lib\site-packages\caiman\components_evaluation.py in estimate_components_quality_auto(Y, A, C, b, f, YrA, frate, decay_time, gSig, dims, dview, min_SNR, r_values_min, r_values_lowest, Npeaks, use_cnn, thresh_cnn_min, thresh_cnn_lowest, thresh_fitness_delta, min_SNR_reject, gSig_range)
    536     _, _, fitness_raw, _, r_values = estimate_components_quality(
    537         traces, Y, A, C, b, f, final_frate=frate, Npeaks=Npeaks, r_values_min=r_values_min, fitness_min=fitness_min,
--> 538         fitness_delta_min=thresh_fitness_delta, return_all=True, dview=dview, num_traces_per_group=50, N=N_samples)
    539 
    540     comp_SNR = -norm.ppf(np.exp(fitness_raw / N_samples))

~\Anaconda3\envs\caiman\lib\site-packages\caiman\components_evaluation.py in estimate_components_quality(traces, Y, A, C, b, f, final_frate, Npeaks, r_values_min, fitness_min, fitness_delta_min, return_all, N, remove_baseline, dview, robust_std, Athresh, thresh_C, num_traces_per_group)
    694                 if 'multiprocessing' in str(type(dview)):
    695                     res = dview.map_async(
--> 696                         evaluate_components_placeholder, params).get(4294967)
    697                 else:
    698                     res = dview.map_sync(evaluate_components_placeholder, params)

~\Anaconda3\envs\caiman\lib\multiprocessing\pool.py in get(self, timeout)
    642             return self._value
    643         else:
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

~\Anaconda3\envs\caiman\lib\multiprocessing\pool.py in _handle_tasks(taskqueue, put, outqueue, pool, cache)
    422                         break
    423                     try:
--> 424                         put(task)
    425                     except Exception as e:
    426                         job, idx = task[:2]

~\Anaconda3\envs\caiman\lib\multiprocessing\connection.py in send(self, obj)
    204         self._check_closed()
    205         self._check_writable()
--> 206         self._send_bytes(_ForkingPickler.dumps(obj))
    207 
    208     def recv_bytes(self, maxlength=None):

~\Anaconda3\envs\caiman\lib\multiprocessing\reduction.py in dumps(cls, obj, protocol)
     49     def dumps(cls, obj, protocol=None):
     50         buf = io.BytesIO()
---> 51         cls(buf, protocol).dump(obj)
     52         return buf.getbuffer()
     53 

OverflowError: cannot serialize a bytes object larger than 4 GiB
`

**Comment by epnev** [comment]
ok, that's a different thing. @pgunn is this related to #335 ?

**Comment by pgunn** [comment]
It seems plausible. 335 points to another issue though that suggests Python3 might not have the issue (although that may be wrong).

Looks like the issue was fixed after version 3 of the pickle format:
https://hg.python.org/cpython/file/2d8e4047c270/Modules/_pickle.c#l1958

but I'm not sure what the default version of the protocol is (guessing 3?)

**Comment by jtalley24** [comment]
Have spent the last few days trying any combination of the above parameter settings.  Also tried reducing `n_processes` from 24 to 12.  Still receiving the above Overflow error, a Memory error, or simply my machine crashes when running any more than ~10 videos in sequence.  For reference, our daily sessions contain ~250 of these videos, each about 15 seconds long and 480x752 pixels.  

Does my machine (6 cores, 3.70 ghz base speed, 64 GB memory, NVIDIA GeForce GTX 1070) simply not have the processing power for concatenated analysis of this scale, or are there other solutions I may try?

**Comment by epnev** [comment]
@jtalley24 You can try reducing further the number of processes although that will decrease the overall processing speed. There is always a tradeoff between memory requirements and processing speed. In any case, 250 videos of 15s each (assuming a frame rate of 10Hz or similar) of 1p data is beyond what the software can currently handle jointly on a standalone machine with 64GB. You can find the setup that will give you the best performance for your machines and stick to that while we work on some long term solutions to these issues. You can also consider spatially decimating your movies to reduce memory consumption.
