### ISSUE TITLE
Very slow performance following CaImAn update

### ISSUE THREAD

**Issue by PhilippBartel** [flatironinstitute/CaImAn#450]
- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), and working environment (Spyder/Jupyter Notebook/other)**
Windows10, Python3.6 (Anaconda Distribution), Jupyter Notebook

- **Describe the issue that you are experiencing**
Following a successful update to the latest version of CaImAn, CaImAn slowed down very considerably. Everything, including rigid motion correction, takes tens of minutes where previously the same routines ran much quicker.
Where should I look to debug this and gain the speed back?

- **Copy error log below**
n/a

**Comment by pgunn** [comment]
Hi,
How did you perform the install? Did you make a new Conda environment? Did anything else change in your configuration at the same time?

**Comment by PhilippBartel** [comment]
Hi,

I have done the following:
1. Uninstalled previous Anaconda/Python and caiman
2. Downloaded the CLI tools for VS2017
3. Downloaded the latest Python 3.6 Anaconda installer and checked the PATH management (as recommended)
4. Then followed the installation procedures (including creation of a new caiman-specific environment)
5. Before creating the caiman environment I installed pytorch in the base environment.
6. The only 2 hiccups were:
    a. caimanmanager had to be explicitly pointed to in the Anaconda/envs; but it worked in the end.
    b. The "build" folder had to be added to the Program Files(x86)/Microsoft Visual Studio/2017/Community/VS/Auxiliary since vsvarsall.bat was under 2017/BuildTools/VC/Auxiliary/Build

I have CUDA on the system, but I did not set up the experimental CUDA environment if that is of any relevance.

Nothing else has changed.

Thanks!

**Comment by pgunn** [comment]
It should not have been necessary to uninstall Anaconda itself (just deleting the caiman environment would have been sufficient). Likewise, reinstalling Visual Studio should be unharmful but unnecessary.

I don't understand what you mean in step 6a - can you elaborate on that a bit?

Are you comparing performance using our test data or your data?

**Comment by PhilippBartel** [comment]
I had some trouble updating and decided to simply reinstall everything :D
6.a. There was a copy of caimanmanager.py in the users/username/CaImAn/ folder and it was being executed when I followed the instructions. Trying to execute it gave an error about not finding oasis. 
So I ran the C:/users/username/Anaconda3/envs/caiman/bin/caimanmanager.py instead and it all worked.

I have run comparisons with the provided demo notebooks and some of my pre-update code on demoMovie.tif , data_endoscope.tif and on my own 2p data (around 26mb so file size is unlikely to be an issue).

**Comment by pgunn** [comment]
Hi,
Another developer on a Mac let me know that he's been seeing performance issues as well with a recent upgrade; we're going to need to look into this. We'll update this ticket as soon as we have more info.

--Pat

**Comment by PhilippBartel** [comment]
Great, thank you!

**Comment by wmau** [comment]
I'm not sure if this is related, but I get severe performance issues when I run a script in Spyder versus when I serially execute cells of code, particularly at the motion correction step.

**Comment by epnev** [comment]
@wmau Do you mean that running things in spyder is slower compared to running from the command prompt?

**Comment by wmau** [comment]
@pgunn Sorry, I mean that when I hit Run File (runfile('SCRIPT_NAME.py')) is slower than running cell blocks one by one, both in Spyder.

**Comment by epnev** [comment]
@PhilippBartel @wmau What do you get if you type in your command prompt (inside your environment)
```
conda list ipykernel
```
?

**Comment by wmau** [comment]
![image](https://user-images.githubusercontent.com/12157943/52669148-5f219100-2ee3-11e9-90d4-256dd1f1a0da.png)

**Comment by epnev** [comment]
@wmau Thanks. We think that downgrading `ipykernel` should resolve the issue. See for example [here](https://github.com/spyder-ide/spyder/issues/7049). Unfortunately, a new environment will likely need to be created. I made the changes in the environment file with 1f5b22f0d50f82dfc359ac2aea8278b338536143 and will merge into the master branch tomorrow.

**Comment by PhilippBartel** [comment]
I'm currently not at the workstation but I will let you know within 24 hrs!

**Comment by PhilippBartel** [comment]
Same here!
![untitled](https://user-images.githubusercontent.com/8902312/52704103-ba9d5e80-2f77-11e9-96c8-107f8fd24100.png)

Simply downgrading the ipykernel within the existing env didn't solve it for me. Could you tell me what you think I should do exactly?

**Comment by epnev** [comment]
@PhilippBartel We need to look into this a bit more, but you might need to create a new environment from scratch. By the way, are your environment variables set before launching python?
```
set MKL_NUM_THREADS=1
set OPENBLAS_NUM_THREADS=1
```

**Comment by PhilippBartel** [comment]
@epnev 

Yes, the environmet variables were set.
Removed the previous caiman environment, created a new one, downgraded ipykernel and installed caiman. Now caimanmanager.py is not finding *past* for some reason. I'm not sure how to debug this.

Tell me if I can do some test that will facilitate the process here :D

**Comment by pgunn** [comment]
@PhilippBartel Are you sure you made the new environment from the environment.yml? That yml file lists "future" in its package lists and the future package implements past (some sly joke among the python devs here I think).

Marker:
When you're in the caiman environment, `conda list` should show a package called 'future' in the list.

**Comment by epnev** [comment]
@PhilippBartel Sorry, I was not clear. What I meant is that you will need to create a new environment, where ipykernel is pinned to the older version right from the environment file. [We have updated the code to do that.](https://github.com/flatironinstitute/CaImAn/blob/master/environment.yml) 
If you don't mind trying again, I think this should help.

**Comment by johannesmaxkappel** [comment]
Not sure whether to open a seperate ticket for this: I experience the same issues as @PhilippBartel described after updating today. For the update, I first updated Anaconda, then deleted the old caiman env and made a clean reinstall. I am running CaImAn on a Windows 10, Python 3.6 as well, NOT through ipython but running *.py scripts in PyCharm IDE with Anaconda environment. I used the same data and the same set of parameters as before and the motion correction takes at least 10x longer.

**Comment by epnev** [comment]
@johannesmaxkappel That's good to hear. We're considering to make pycharm our default recommendation for users, although that might involve a somewhat steep learning curve for python novices.

**Comment by epnev** [comment]
@PhilippBartel Any updates? Have your tried installing on a new environment to see whether the problems persist?

**Comment by epnev** [comment]
@PhilippBartel Closing due to inactivity. Feel free to reopen if you're still encountering problems.
